Repository PracticaDS/pdes-tp-anonymous, pull requests merged in 2019-06, with the labels that each got.

#52 Issue 49 add new user service
  .travis.yml
  back/.eslintrc
  back/package.json
  back/src/app/index.js
  back/src/index.js
  back/src/models/user.js
  back/test/index.js
  back/yarn.lock
Labels: enhancement

#54 Issue 53 get factories service
  back/.eslintrc
  back/.gitignore
  back/package.json
  back/src/app/express.js
  back/src/app/index.js
  back/src/app/mongoose.js
  back/src/app/routes.js
  back/src/index.js
  back/src/model/user.controller.js
  back/src/model/user.js
  back/src/models/user.js
  back/test/index.js
  back/test/user.js
  back/yarn.lock
Labels: enhancement

#64 Issue 55 add all services
  back/.eslintrc
  back/src/app/routes.js
  back/src/model/user.controller.js
  back/test/home.test.js
  back/test/test-case.js
  back/test/user-games.test.js
  back/test/user.test.js
Labels: enhancement

#66 added move
  front/src/actions/toolboxActions.js
  front/src/components/ToolBox/Actions/Action.jsx
  front/src/components/ToolBox/Actions/Move.jsx
  front/src/components/WorkingArea/EngineGrid/Machine.jsx
  front/src/components/__tests__/ToolBox/Actions/Move.spec.jsx
  front/src/components/__tests__/ToolBox/Actions/Remove.spec.jsx
  front/src/reducers/__tests__/executeAction.spec.js
  front/src/reducers/__tests__/toolboxReducer.spec.js
  front/src/reducers/executeAction.js
  front/src/reducers/toolboxReducer.js
Labels: enhancement

#78 Dependencies upgrade
  front/yarn.lock
Labels: enhancement

#79 added dropdown with recipes
  front/src/components/ToolBox/Machines/Crafter.jsx
  front/src/components/ToolBox/Machines/Starter.jsx
  front/src/components/__tests__/ToolBox/Machines/Crafter.spec.jsx
  front/src/components/__tests__/ToolBox/Machines/Starter.spec.jsx
  front/src/reducers/__tests__/executeAction.spec.js
  front/src/reducers/executeAction.js
Labels: enhancement

#80 Fix routes
  .pdes/README.md
  README.md
  back/src/app/routes.js
  back/src/model/user.controller.js
  back/test/home.test.js
  back/test/test-case.js
  back/test/user-games.test.js
  back/test/user.test.js
Labels: bug

#81 Issue 67 create login
  back/package.json
  back/src/app/express.js
  back/yarn.lock
  front/package.json
  front/src/app/App.jsx
  front/src/app/Routes.jsx
  front/src/components/Game/Game.jsx
  front/src/components/User/CreateGame.css
  front/src/components/User/CreateGame.jsx
  front/src/components/User/Login.css
  front/src/components/User/Login.jsx
  front/src/components/User/UserProfile.css
  front/src/components/User/UserProfile.jsx
  front/src/components/__tests__/Game/Game.spec.jsx
  front/src/components/__tests__/User/CreateGame.spect.jsx
  front/src/components/__tests__/User/Login.spec.jsx
  front/src/components/__tests__/User/UserProfile.spec.jsx
  front/yarn.lock
Labels: enhancement

#83 Se saco el routes y se configuro el router para github pages
  front/.eslintrc
  front/src/app/App.jsx
  front/src/app/Routes.jsx
  front/src/components/User/Login.jsx
  front/yarn.lock
Labels: bug

#84 Added middleward with prometheus
  back/package.json
  back/src/app/express.js
  back/yarn.lock
Labels: config

#85 Issue 68 connect front with back
  front/src/app/Routes.jsx
  front/src/app/Service.jsx
  front/src/components/User/CreateGame.jsx
  front/src/components/User/Login.jsx
  front/src/components/User/UserProfile.jsx
  front/src/components/__tests__/WorkingArea/WorkingArea.spec.jsx
  front/yarn.lock
Labels: enhancement

#87 Issue 86 create button save game
  front/package.json
  front/src/actions/toolboxActions.js
  front/src/app/App.css
  front/src/components/Game/Game.jsx
  front/src/components/User/UserProfile.css
  front/src/components/WorkingArea/WorkingArea.css
  front/src/components/WorkingArea/WorkingArea.jsx
  front/src/components/__tests__/Game/Game.spec.jsx
  front/src/components/__tests__/WorkingArea/EngineGrid/Machine.spec.jsx
  front/src/reducers/__tests__/toolboxReducer.spec.js
  front/src/reducers/toolboxReducer.js
Labels: enhancement

#93 Issue 88 docker front
  .docker/front/Dockerfile
  back/package.json
  front/package.json
  front/src/app/App.jsx
  front/src/app/Routes.jsx
  front/src/app/Service.jsx
  front/yarn.lock
Labels: enhancement

#95 Issue 90 docker compose
  .docker/back/Dockerfile
  .docker/compose/docker-compose.yml
  .docker/front/Dockerfile
  back/package.json
Labels: enhancement

#96 Building Docker Containers from travis
  .travis.yml
  .travis/build_front.sh
  .travis/deploy_back.sh
  .travis/docker_and_deploy.sh
Labels: enhancement

#97 Fixing env vars on building web docker container
  .travis/docker_and_deploy.sh
Labels: enhancement

#99 Fixing
  .docker/compose/docker-compose.yml
  .docker/front/Dockerfile
  .travis/docker_and_deploy.sh
  back/yarn.lock
Labels: bug

#101 Cambios
  .docker/back/Dockerfile
  .docker/compose/docker-compose.yml
  .docker/front/Dockerfile
  .travis/docker_and_deploy.sh
Labels: enhancement

#103 Issue 102 env config
  .docker/compose/docker-compose.yml
  .docker/front/Dockerfile
  .travis/docker_and_deploy.sh
  front/public/config.js
  front/public/index.html
  front/src/app/Service.jsx
Labels: enhancement
